class Gemstone {
  final String name;
  final String color;
  final double hardness;
  final String origin;
  final String shortDescription;
  final String longDescription;
  final String imgPath;
  final String iconPath;
  final String category;
  final String formula;
  final String crystalSystem;
  final String crystalClass;
  final String spaceGroup;
  final String identificationColor;
  final String crystalHabit;
  final String cleavage;
  final String fracture;
  final String tenacity;
  final double mohsScaleHardness;
  final String luster;
  final String streak;
  final String diaphaneity;
  final String specificGravity;
  final String opticalProperties;
  final String refractiveIndex;
  final String birefringence;
  final String pleochroism;
  final double dispersion;
  final String ultravioletFluorescence;
  final String commonImpurities;

  Gemstone({
    required this.name,
    required this.color,
    required this.hardness,
    required this.origin,
    required this.shortDescription,
    required this.longDescription,
    required this.imgPath,
    required this.iconPath,
    required this.category,
    required this.formula,
    required this.crystalSystem,
    required this.crystalClass,
    required this.spaceGroup,
    required this.identificationColor,
    required this.crystalHabit,
    required this.cleavage,
    required this.fracture,
    required this.tenacity,
    required this.mohsScaleHardness,
    required this.luster,
    required this.streak,
    required this.diaphaneity,
    required this.specificGravity,
    required this.opticalProperties,
    required this.refractiveIndex,
    required this.birefringence,
    required this.pleochroism,
    required this.dispersion,
    required this.ultravioletFluorescence,
    required this.commonImpurities,
  });
}

List<Gemstone> gemstones = [
  Gemstone(
    name: 'Amethyst',
    color: 'Purple',
    hardness: 7.0,
    origin: 'Brazil',
    shortDescription: 'A violet variety of quartz often used in jewelry.',
longDescription: "Amethyst, revered for its majestic hue reminiscent of royalty, has been esteemed throughout history, from ancient Egypt to the British crown jewels. This gemstone's color spectrum ranges from deep, eggplant purple to the soft lavender of early dawn, making it highly coveted in both rough and polished forms. Ancient Greeks believed amethyst could prevent intoxication, embedding the stone in drinking vessels to ward off the effects of wine. Beyond its beauty, amethyst is considered a stone of protection and purification, purported to clear negative energies and foster a serene environment for its bearer. It's also known as the stone of St. Valentine, symbolizing faithful love.",    imgPath: '../assets/images/Amethyst.png',
    iconPath: '../assets/icons/amethystC.png',
    category: 'Oxide mineral variety',
    formula: 'aluminium oxide with chromium, Al2O3:Cr',
    crystalSystem: 'Trigonal',
    crystalClass: 'Hexagonal scalenohedral (3m)',
    spaceGroup: 'R3c[1]',
    identificationColor: 'Orangy red through strongly purplish red.',
    crystalHabit: 'Terminated tabular hexagonal prisms',
    cleavage: 'No true cleavage',
    fracture: 'Conchoidal, splintery',
    tenacity: 'Brittle',
    mohsScaleHardness: 9.0,
    luster: 'Subadamantine, vitreous, pearly (on partings)',
    streak: 'White',
    diaphaneity: 'Transparent, translucent',
    specificGravity: '3.97–4.05',
    opticalProperties: 'Uniaxial/−',
    refractiveIndex: 'nω=1.768–1.772, nε=1.760–1.763',
    birefringence: '0.008 to 0.010',
    pleochroism: 'Strong: purplish-red – orangy-red',
    dispersion: 0.018,
    ultravioletFluorescence: 'Red under longwave',
    commonImpurities: '',
  ),
  Gemstone(
    name: 'Ametrine',
    color: 'Yellow and purple',
    hardness: 7.0,
    origin: 'Bolivia',
    shortDescription: 'A unique stone combining amethyst and citrine.',
longDescription: "Ametrine is a rare marvel where amethyst and citrine coexist within a single crystal, blending their violet and yellow hues in a captivating dance of color. This gemstone embodies balance, symbolizing the harmonious integration of masculine and feminine energies. Its origin story is as enchanting as the stone itself, rooted in South American lore where it was believed to have been discovered in the treasures of a conquistador. Today, ametrine is prized not only for its rarity and beauty but also for its purported metaphysical properties, including enhancing creativity, dissolving negativity, and promoting inner peace.",    imgPath: '../assets/images/ametrine.png',
    iconPath: '../assets/icons/ametrineC.png', 
    category: 'Quartz',
    formula: 'SiO2',
    crystalSystem: 'Trigonal',
    crystalClass: 'Hexagonal scalenohedral (3m)',
    spaceGroup: 'P31c',
    identificationColor: 'Purple and yellow or orange',
    crystalHabit: 'Hexagonal prisms terminated by complex pyramids',
    cleavage: 'Indistinct',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 7.0,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent',
    specificGravity: '2.65',
    opticalProperties: 'Uniaxial (+)',
    refractiveIndex: 'nω = 1.544–1.553, nε = 1.553–1.554',
    birefringence: '0.009',
    pleochroism: 'Weak dichroism',
    dispersion: 0.013,
    ultravioletFluorescence: 'None',
    commonImpurities: 'Iron',
  ),
  Gemstone(
    name: 'Black Spinel',
    color: 'Black',
    hardness: 8.0,
    origin: 'Thailand',
    shortDescription: 'A rare gemstone made up of hard vitreous magnesium oxide.',
longDescription: "Black Spinel offers a mirror to the soul, its dark facade reflecting the depths of the night sky. Unlike many gems, black spinel is one of the few true black gemstones, embodying strength, tenacity, and the power of rejuvenation. It’s a protective stone that's said to repel negativity while inspiring empowerment without overwhelming. Historically, spinel was mistaken for ruby or sapphire; however, it has since claimed its rightful place in the gemstone kingdom for its unique properties and the intense depth of its color.",    imgPath: '../assets/images/black_spinel.png',
    iconPath: '../assets/icons/black_spinelC.png',
    category: 'Oxide mineral variety',
    formula: 'MgAl2O4',
    crystalSystem: 'Isometric',
    crystalClass: 'Hexoctahedral (m3m)',
    spaceGroup: 'Fd3m',
    identificationColor: 'Black',
    crystalHabit: 'Massive to crystalline',
    cleavage: 'Indistinct',
    fracture: 'Conchoidal to uneven',
    tenacity: 'Brittle',
    mohsScaleHardness: 8.0,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent to opaque',
    specificGravity: '3.58–4.10',
    opticalProperties: 'Isotropic',
    refractiveIndex: 'n = 1.719–1.730',
    birefringence: 'None',
    pleochroism: 'None',
    dispersion: 0.020,
    ultravioletFluorescence: 'None',
    commonImpurities: 'Fe, Zn, Mn, Cr, Ti, Ga, V, Sc',
  ),
  Gemstone(
    name: 'Blue Sapphire',
    color: 'Blue',
    hardness: 9.0,
    origin: 'Sri Lanka',
    shortDescription: 'One of the most popular colored stones, known for its deep blue hue and durability.',
longDescription: "Blue Sapphire, with its deep azure blue, has been a symbol of the heavens, a guardian of innocence, and a bestower of truth and good health. It's as if the sky solidified into a tangible form, capturing the essence of an endless summer's day. Kings wore sapphires around their necks as a powerful defense from harm. It's believed to attract divine favor and wise judgment, with its celestial hues signifying the height of celestial hope and faith. Sapphires are thought to bring protection, good fortune, and spiritual insight, a bridge between earth and the cosmos.",    imgPath: '../assets/images/blue_sapphire.png',
    iconPath: '../assets/icons/sapphireC.png',
    category: 'Oxide mineral variety',
    formula: 'Al2O3',
    crystalSystem: 'Trigonal',
    crystalClass: 'Hexagonal scalenohedral (3m)',
    spaceGroup: 'R3c',
    identificationColor: 'Blue',
    crystalHabit: 'Tabular, bipyramidal, prismatic crystals',
    cleavage: 'None',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 9.0,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent to opaque',
    specificGravity: '3.95–4.03',
    opticalProperties: 'Uniaxial (−)',
    refractiveIndex: 'nω = 1.767–1.774, nε = 1.759–1.769',
    birefringence: '0.008',
    pleochroism: 'Strong: blue, violet-blue, greenish-blue',
    dispersion: 0.018,
    ultravioletFluorescence: 'Red, inert',
    commonImpurities: 'Iron, titanium',
  ),
  Gemstone(
    name: 'Citrine',
    color: 'Yellow',
    hardness: 7.0,
    origin: 'Brazil',
    shortDescription: 'A pale yellow to brownish orange variety of quartz, popular for its color and affordability.',
longDescription: "Citrine, glowing with the warmth of the sun, shines bright with joy, abundance, and transmutative energy. This gemstone is said to carry the power of the sun itself, never needing to cleanse itself of negativity because it is believed to transmute, dissipate, and ground it. Citrine energizes every level of life, cleansing the chakras and opening the intuition. It attracts wealth, prosperity, and success, inspiring one to achieve their goals. In ancient times, it was used as a charm against snake venom and evil thoughts.",    imgPath: '../assets/images/Citrine.png',
    iconPath: '../assets/icons/citrineC.png',
    category: 'Quartz',
    formula: 'SiO2',
    crystalSystem: 'Trigonal',
    crystalClass: 'Hexagonal scalenohedral (3m)',
    spaceGroup: 'P3121',
    identificationColor: 'Yellow to brownish orange',
    crystalHabit: 'Prismatic, massive',
    cleavage: 'None',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 7.0,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent to translucent',
    specificGravity: '2.65',
    opticalProperties: 'Uniaxial (+)',
    refractiveIndex: 'nω = 1.544–1.553, nε = 1.553–1.554',
    birefringence: '0.009',
    pleochroism: 'Weak dichroism',
    dispersion: 0.013,
    ultravioletFluorescence: 'None',
    commonImpurities: 'Iron',
  ),
  Gemstone(
    name: 'Diamond',
    color: 'Colorless',
    hardness: 10.0,
    origin: 'Botswana',
    shortDescription: 'The hardest and most brilliant of all gemstones, often used in engagement rings.',
longDescription: "Diamond, born from the depths of the earth under extreme conditions, emerges as a symbol of purity, invincibility, and everlasting love. The hardest known natural material, diamonds have been celebrated for their durability and brilliance, symbolizing the steadfastness of love. Throughout history, diamonds have adorned the crowns of royalty and the rings of lovers, encapsulating moments of intense joy and commitment. Beyond their unmatched beauty, diamonds are thought to bring courage and strength to their wearers, reflecting the resilience and eternity of the stone itself.",    imgPath: '../assets/images/diamond.png',
    iconPath: '../assets/icons/diamondC.png',
    category: 'Native element mineral',
    formula: 'C',
    crystalSystem: 'Cubic',
    crystalClass: 'Hexoctahedral (m3m)',
    spaceGroup: 'Fd3m',
    identificationColor: 'Colorless, yellow, brown, gray, black, blue, green, orange, pink, purple, red, violet, and combinations thereof',
    crystalHabit: 'Octahedral, cubic, and dodecahedral crystals, massive',
    cleavage: 'Perfect and good in 4 directions',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 10.0,
    luster: 'Adamantine',
    streak: 'White',
    diaphaneity: 'Transparent to subtransparent',
    specificGravity: '3.52',
    opticalProperties: 'Isotropic',
    refractiveIndex: '2.418 (at 500 nm)',
    birefringence: 'None',
    pleochroism: 'None',
    dispersion: 0.044,
    ultravioletFluorescence: 'Blue, sometimes weak; in longwave and shortwave ultraviolet light',
    commonImpurities: 'Nitrogen, boron',
  ),
  Gemstone(
    name: 'Emerald',
    color: 'Green',
    hardness: 7.5,
    origin: 'Colombia',
    shortDescription: 'Known for its lush green color, emeralds are prized in jewelry and have been since ancient times.',
longDescription: "Emerald, with its lush green hues, embodies the renewing cycle of life and the lush landscapes of Earth itself. This gemstone was Cleopatra's favorite, and its rich green color symbolizes growth, reflection, peace, and balance. Emerald's green is the color of spring and has long symbolized love and rebirth. As the gem of Venus, it was also considered to aid in fertility. In ancient Rome, it was the color of Venus, the goddess of beauty and love.",    imgPath: '../assets/images/Emerald.png',
    iconPath: '../assets/icons/emeraldC.png',
    category: 'Silicate mineral',
    formula: 'Be3Al2(SiO3)6',
    crystalSystem: 'Hexagonal',
    crystalClass: 'Dihexagonal dipyramidal (6/mmm)',
    spaceGroup: 'P6/mmc',
    identificationColor: 'Vivid green',
    crystalHabit: 'Prismatic crystals, terminated by small pyramids',
    cleavage: 'None',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 7.5,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent to translucent',
    specificGravity: '2.67–2.78',
    opticalProperties: 'Uniaxial (+)',
    refractiveIndex: 'nω = 1.564–1.595, nε = 1.568–1.602',
    birefringence: '0.006 to 0.009',
    pleochroism: 'Weak to distinct',
    dispersion: 0.014,
    ultravioletFluorescence: 'Inert',
    commonImpurities: 'Iron, vanadium, chromium',
  ),
  Gemstone(
    name: 'Pearl',
    color: 'White or cream',
    hardness: 2.5,
    origin: 'Japan',
    shortDescription: 'A classic gemstone produced within the soft tissue of a living shelled mollusk.',
longDescription: "Pearl, unlike other gemstones, is a maritime marvel that encapsulates the serene beauty of the ocean. Pearls are formed within the shell of certain mollusks as a defense mechanism against potentially threatening irritants. They symbolize wisdom acquired through experience, offering protection and attracting good luck and wealth. They're also known for their calming effects and their ability to balance one's karma. Pearls have adorned the regal and the divine for centuries, symbolizing purity, spiritual transformation, and the sacred feminine.",    imgPath: '../assets/images/Pearl.png',
    iconPath: '../assets/icons/Pearl-icon.png',
    category: 'Organic mineral',
    formula: 'C5H7NO3',
    crystalSystem: 'Orthorhombic',
    crystalClass: 'Dipyramidal (mmm)',
    spaceGroup: 'Pna21',
    identificationColor: 'White, cream, yellow, orange, pink, blue, green, silver, black, gray, gold, purple, iridescent',
    crystalHabit: 'Irregular',
    cleavage: 'None',
    fracture: 'Irregular to conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 2.5,
    luster: 'Pearly',
    streak: 'White',
    diaphaneity: 'Opaque',
    specificGravity: '2.60–2.85',
    opticalProperties: 'Biaxial',
    refractiveIndex: 'nα = 1.530–1.685, nβ = 1.520–1.686, nγ = 1.530–1.686',
    birefringence: '0.010–0.015',
    pleochroism: 'None',
    dispersion: 0.018,
    ultravioletFluorescence: 'Variable',
    commonImpurities: 'None',
  ),
  Gemstone(
    name: 'Peridot',
    color: 'Green',
    hardness: 7.0,
    origin: 'Egypt',
    shortDescription: 'A gem-quality olivine known for its striking olive or lime green color.',
longDescription: "Peridot, often called the evening emerald for its radiant green color that doesn't fade at night, carries the gift of inner radiance, sharpening the mind and opening it to new levels of awareness. Formed under extreme conditions in the Earth’s mantle, peridot is brought to the surface by volcanic activity, embodying the fiery birth of Mother Earth. This stone is associated with the sun, helping to dissipate personal darkness through the understanding of the light within.",    imgPath: '../assets/images/Peridot.png',
    iconPath: '../assets/icons/peridotC.png',
    category: 'Silicate mineral',
    formula: '(Mg, Fe)2SiO4',
    crystalSystem: 'Orthorhombic',
    crystalClass: 'Dipyramidal (mmm)',
    spaceGroup: 'Pbnm',
    identificationColor: 'Olive green, yellow-green, lime green',
    crystalHabit: 'Granular',
    cleavage: 'Poor',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 7.0,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent to translucent',
    specificGravity: '3.27–3.48',
    opticalProperties: 'Biaxial (+)',
    refractiveIndex: 'nα = 1.650–1.690, nβ = 1.653–1.693, nγ = 1.670–1.712',
    birefringence: '0.018–0.030',
    pleochroism: 'Weak',
    dispersion: 0.020,
    ultravioletFluorescence: 'None',
    commonImpurities: 'Iron, nickel, chromium',
  ),
  Gemstone(
    name: 'Rose Quartz',
    color: 'Pink',
    hardness: 7.0,
    origin: 'Brazil',
    shortDescription: 'A type of quartz that exhibits a pale pink to rose red hue.',
longDescription: "Rose Quartz, the stone of unconditional love, radiates soft, healing energy that nurtures the heart at all levels. It provides a deep sense of personal fulfillment and contentment, allowing one the capacity to truly give and receive love from others. Known as a romance stone, rose quartz can be used to attract love. It also helps develop a closer bond with family and friends. It carries a soft feminine energy of compassion and peace.",    imgPath: '../assets/images/Rose_Quartz.png',
    iconPath: '../assets/icons/rose_quartzC.png',
    category: 'Oxide mineral variety',
    formula: 'Silicon dioxide, SiO2',
    crystalSystem: 'Trigonal',
    crystalClass: 'Hexagonal scalenohedral (3m)',
    spaceGroup: 'R3c',
    identificationColor: 'Pale pink to rose red',
    crystalHabit: 'Massive',
    cleavage: 'None',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 7.0,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent to translucent',
    specificGravity: '2.65',
    opticalProperties: 'Uniaxial (+)',
    refractiveIndex: 'nω = 1.544–1.553, nε = 1.553–1.554',
    birefringence: '0.009',
    pleochroism: 'Weak',
    dispersion: 0.013,
    ultravioletFluorescence: 'None',
    commonImpurities: 'Iron, titanium, manganese',
  ),
  Gemstone(
    name: 'Ruby',
    color: 'Red',
    hardness: 9.0,
    origin: 'Myanmar',
    shortDescription: 'A precious stone known for its vibrant red color and hardness, second only to diamond.',
longDescription: "Ruby, a talisman of passion, protection, and prosperity, has been revered throughout history for its vibrant red hue. It symbolizes the sun, and its glowing hue suggests an inextinguishable flame within the stone that legends claim would shine through even the thickest clothing and could not be hidden. Rubies have been possessed by emperors and kings throughout the ages as symbols of wealth and success in love.",    imgPath: '../assets/images/ruby.png',
    iconPath: '../assets/icons/rubyC.png',
    category: 'Oxide mineral variety',
    formula: 'Al2O3',
    crystalSystem: 'Trigonal',
    crystalClass: 'Hexagonal scalenohedral (3m)',
    spaceGroup: 'R3c',
    identificationColor: 'Red',
    crystalHabit: 'Tabular, bipyramidal, prismatic crystals',
    cleavage: 'None',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 9.0,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent to opaque',
    specificGravity: '3.97–4.05',
    opticalProperties: 'Uniaxial (−)',
    refractiveIndex: 'nω = 1.767–1.774, nε = 1.759–1.769',
    birefringence: '0.008',
    pleochroism: 'Strong: purplish-red – orangy-red',
    dispersion: 0.018,
    ultravioletFluorescence: 'Red under longwave',
    commonImpurities: '',
  ),
  Gemstone(
    name: 'Smoky Quartz',
    color: 'Brown to black',
    hardness: 7.0,
    origin: 'Brazil',
    shortDescription: 'A dark variety of quartz known for its clarity and smoky color.',
longDescription: "Smoky Quartz, with its earthy tones, grounds and stabilizes the wearer, bringing a sense of calm and serenity. It gently heals emotional conditions and trauma, absorbs negativities, and promotes positive thoughts and action. Historically used as a stone of power, smoky quartz offers a transparent shield against psychic attack. It is believed to be connected to the power of Mother Earth herself, grounding the wearer to the natural world and providing a link between heaven and earth.",    imgPath: '../assets/images/Smoky_Quartz.png',
    iconPath: '../assets/icons/smoky_quartzC.png',
    category: 'Oxide mineral variety',
    formula: 'Silicon dioxide, SiO2',
    crystalSystem: 'Trigonal',
    crystalClass: 'Hexagonal scalenohedral (3m)',
    spaceGroup: 'P3121',
    identificationColor: 'Brown to black',
    crystalHabit: 'Prismatic, fibrous, granular',
    cleavage: 'None',
    fracture: 'Conchoidal',
    tenacity: 'Brittle',
    mohsScaleHardness: 7.0,
    luster: 'Vitreous',
    streak: 'White',
    diaphaneity: 'Transparent to translucent',
    specificGravity: '2.65',
    opticalProperties: 'Uniaxial (+)',
    refractiveIndex: 'nω = 1.544–1.553, nε = 1.553–1.554',
    birefringence: '0.009',
    pleochroism: 'Weak to moderate',
    dispersion: 0.013,
    ultravioletFluorescence: 'None',
    commonImpurities: 'Iron',
  ),
];
